name: antio_books
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  card_swiper: ^3.0.1
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.7
  go_router: ^13.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
